### ISSUE TITLE
Distract the guards

### ISSUE THREAD

**Issue by haleyk10198** [ivanseed/google-foobar-help#10]
There is a problem on level 4 called "distract the guards" where it's about graph matching and math theory called distracted the guards. Although my code got AC but I've also found a counter case soon after submission. I figured out that I need some math theory expert to help me complete the puzzle and stop it from haunting me. (´･_･`)

Here's part of the problem: given a pair (x, y), f(x, y) = f(2x, y-x) if x < y else f(y, x). Determine if f(x, y) will end up in the state f(a, a). My partial solution determined it by considering if (x+y)/min(x,y) is a power of 2, but it fails in my custom case [9,15]. I had some discussions with others and figured out the correct determine function maybe (x+y)/gcd(x,y) intuitively, but we just can't find a solid proof to back it up. Thanks in advance to anyone who would share some thoughts about this problem.

**Comment by haleyk10198** [comment]
Oh, I forgot the constraints. There's about 10000 pairs to check, and 0 < x,y < 2^30. x,y are both integer.

**Comment by MGutensohn** [comment]
I did something similar to MitalAshoks solution and it's not passing the 3rd test case.

**Comment by haleyk10198** [comment]
There's one thing missing from MitalAshoks solution. Instead of x : y = 1 : Mersenne numbers, it should be x + y = 2 ** Z, as each f doubles the coefficients of x and y. 

So what we should be checking is if x * k = (2**n - k) * y, (x+y) * k = 2**n * y, thus we should check if (x+y) carries a higher power for a common prime factor except 2 than y. If yes, then it will continue forever.

I am not sure if this works though - please let me know the results. :)
(The plus side is at least this fits the tricky case (9, 15))

**Comment by haleyk10198** [comment]
Edit: it should be  x * k = (2^n - k) * y, (x+y) * k = 2^n * y, the formatting got messed up.

**Comment by MitalAshok** [comment]
@haleyk10198 I tested it for all `x` from `1` to `250` with all `y` from `x` to `250`, and `(x + y) / gcd(x, y)` gave the expected results.

Test code: [C++ Gist](https://gist.github.com/MitalAshok/6cd244f65ad27e4844db4b26aab3bfbd)

**Comment by kethorinironfists** [comment]
I've done my check using a log algorithm...
First, notice that f(2x, 2y)=f(x, y), and if (x+y)%2!=0, then they will fight endlessly.
So, if both x and y are odd, you have to simulate one fight, and they'll be even.
If they are both even, just divide then by two.
If they are equal sometime, then they will stop fighting. Simple coding ;)

**Comment by WoodyWangHou** [comment]
@MitalAshok  I feel there is still missing cases where the reverse traverse from `f(x, y) = (a, a)`, in one step upstream (a, a), it is `(2x, y - x)` where y = 3x, and one more step it also be the case (2x + y/2, y/2).

To put this clearer： (a, a) <- (a/2, 3/2 * a) <- (5/4 * a, 3/4 *a). That means (5, 3) will also end up at (4, 4) which does not meet the criteria you mentioned, x : y ratio = 1:3, 1:7 ... 1:(2**n -1). And you idea will probably miss this case. 

Especially, x = 5, y =3 will fail here:
```
if (x % y != 0) {
        return true;
    } // for 5,3, it should return false as they will end up at 4,4
```
