### ISSUE TITLE
 For test cases 3 and 10 f's columns do not match r's rows

### ISSUE THREAD

**Issue by aaronjrenfroe** [ivanseed/google-foobar-help#14]
I've come to the situation where for test 3 and 10 when multiplying f by r,  f's columns do not match r's rows. f is a 4x4 and r is a 6x4 so the step of multiplying f x r cannot take place correctly. 

Other than that, i'm passing all tests.

**Comment by murkythunder** [comment]
If you're talking bout Doomsday Fuel, r in test case 3 is a 4 x 2, not 6 x 4

**Comment by aaronjrenfroe** [comment]
My example I gave in the initial question was for test case 10, my apologies.

**Comment by murkythunder** [comment]
For test case 10, the f matrix is a 6x6.

**Comment by aaronjrenfroe** [comment]
If **_i_** is a 4x4 and 6 is a 6x6 then **_i - q_** is going to be a 4x4, no?
so (i-q)^-1 is also a 4x4

**Comment by murkythunder** [comment]
The identity matrix corresponds to the size of **q** So your identity matrix should be 6x6, with 1s diagonal and 0s everywhere else.

**Comment by aaronjrenfroe** [comment]
Thanks for your help! When I mad the identity matrix the size of **_i_** i passed all the tests. The [help page for doomsday fuel](https://github.com/ivanseed/google-foobar-help/blob/master/challenges/doomsday_fuel/doomsday_fuel.md) lead me to beleave that if the size of the original matrix was 10 and the size of q was 6 then the identy matrix would be 4, ([see this image](https://github.com/ivanseed/google-foobar-help/blob/master/challenges/doomsday_fuel/assets/mat2.png)). Thank you thank you.
