### ISSUE TITLE
doomsday_fuel issue

### ISSUE THREAD

**Issue by Milo24s1** [ivanseed/google-foobar-help#21]
thanks for your detailed explanation. I got an issue regarding the **F = (I-Q)^-1** calculation 

once states are rearranged Q is **[0,1|4,0]**
but when you are going to calculate I-Q , Q is **[0,1/2|4/9,0]**

same for the **I** and **R** as well.

can you tell me the operation you did convert Q and I from first state to next state?
I feel this might be a basic operation that I missed.
Sorry for asking a dumb question.

**Comment by pineman** [comment]
@Milo24s1 The input matrix given by the challenge has only integer number entries, representing the number of times a given state will be followed. However, for this method to work in general, we must work with a matrix that contain probabilities. So, to convert Q to probabilities, it is necessary to divide each row by the sum of that same row. I hope this helps.
