### ISSUE TITLE
Help ?

### ISSUE THREAD

**Issue by stevem99** [ivanseed/google-foobar-help#6]
I have implemented your solution to the best of my ability, however I am only passing half of the tests.

Being as there is no output from the verify command, I'm unsure what I could possibly check for.  Were you able to pass all the tests with your implementation of this solution ?

**Comment by stevem99** [comment]
Okay- I've got mine to the same point as another guy, it is only failing test 6.  Not sure what edge cases I could look out for!

**Comment by ivanseed** [comment]
Hey,

Which problem is this? `doomsday_fuel`? 

Also you should be able to do `if (input > x) { return null; }` and if you still have the same tests failing you can then do `if (input > x) { System.out.println; }` then if you get an error you found out some information about your inputs.

**Comment by stevem99** [comment]
I really appreciate your help.  After putting this in I saw some of the conversation with others in the closed issues.  This input method looks like a java example, do you know if it works in Python ?

Thanks again.

**Comment by ivanseed** [comment]
You will want to throw some conditionals against the argument that you are taking from each test. So for example you are being passed a map `m`.

If you write `if len(m) > 4` and return `null` inside the conditional you will _fail_ all tests which the input was greater than 4 in length. Now lets say you find out by the process of elimination that all your tests pass except number 6 when you write `if len(m) == 1` - you still do not know with 100% certainty that the conditional is passing.

However you can replace the `return null` with `print('foo')` which will cause ANY tests that HIT this line to throw an error. If you get an error, you have found some information about the input that is causing you trouble. If you do not get an error, then that input is not being used by any tests.

You may find that the test you are failing is an edge case, where the map is `[1]` or `[[1,0],[0,1]]`.

**Comment by stevem99** [comment]
Okay- thanks!  That makes sense.  I have sort of been doing that but I thought you had a better trick.

I did catch the m=[[1]] issue, and I do have a check in there for a 2x2 matrix (but it never fires).  I will continue trying to poke for more information about the test case, and maybe review some more of my logic.  I went from not knowing much about matrices to feeling like an expert- okay maybe not but I know a lot more than I ever did  :)  I was reading the scipy and numpy are really the best way to work with matrices in python but we have to do it by hand in foobar.

I will keep at it, wish me luck, I only have approx 1 day remaining.

**Comment by ivanseed** [comment]
Best of luck!

Maybe it could be a fraction that is not being simplified as much as possible, or something is slightly wrong with multiplication/addition.

**Comment by stevem99** [comment]
I was able to identify the problem matrix, I'm tracing thru my code to see if there is some bug..
[[0, 7, 0, 17, 0, 1, 0, 5, 0, 2],
 [0, 0, 29, 0, 28, 0, 3, 0, 16, 0],
 [0, 3, 0, 0, 0, 1, 0, 0, 0, 0],
 [48, 0, 3, 0, 0, 0, 17, 0, 0, 0],
 [0, 6, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

**WARN- Answer looks wrong :( [2, 2, 2, 2, 1, 10]

**Comment by stevem99** [comment]
Okay- after tracing the steps it was a problem with my method of finding the least common denominator for my end result fractions!  *WHEW*
[4, 5, 5, 4, 2, 20]

**Comment by ivanseed** [comment]
I think I ran into a problem with my LCM method too. Glad you figured it out though I can imagine it was very long winded.

**Comment by sreetamdas** [comment]
Hey @stevem99 , how were you able to get the matrix which was failing the test case?

I'm on this challenge myself.

**Comment by stevem99** [comment]
I used ivanseed method of intentionally setting up an error condition, except I combined it with a mapping of each value to a specific exception so I would know what value was being supplied to the program based on the raised exception.  It was kind of a brute-force style attack but I was desperate and it does work.

**Comment by ivanseed** [comment]
I think it would be fair if they allowed to reveal one of the tests per challenge, i.e. if you are failing only 6 and have not used your reveal you could see the inputs just for that test.

**Comment by sreetamdas** [comment]
True, as is the system in Hackerrank, wherein you can trade in your "Hackos" to see test cases
