### ISSUE TITLE
doomsday_fuel tests

### ISSUE THREAD

**Issue by jalepo** [ivanseed/google-foobar-help#9]
Hey,

Thanks so much for the info, I'm really close on this one thanks to you folks.

Unfortunately, I'm still failing tests 3, 9 and 10.

Anyone have any further insight into what is unique about those tests?

**Comment by jalepo** [comment]
Never mind, I got it!

If you are inverting a matrix using the cofactors/adjugate method, be careful how you change the signs on the cofactor matrix.  Just multiplying every other value by -1 will only work for matrices with odd-numbered sizes.  Need to make sure that the second row starts with a negative.

On that note, it would appear that tests 3, 9 and 10 are even sized matrices greater that 2 :)

**Comment by ivanseed** [comment]
Glad you got it! I was thinking that they would randomize the test cases each time 🤔 .

I might write a little script that determines the input for all the tests and put them in the readme so we can see possible inputs, but not sure if Google would appreciate that.
